import { crane } from '@/data/craneLoadCharts'
import { userName } from '@/data/users'
import type { Assessment, Job } from '@/types'
import { SOURCE_LABEL } from './confidence'
import { dateTime, kg, metres, mm, pct } from './format'
import type { LiftCalculation } from './lifting'

/** Plain-text permit, formatted for pasting into a terminal log or radio message. */
export function formatPermitText(a: Assessment, job: Job | undefined, calc: LiftCalculation): string {
  const plan = a.liftPlan
  const c = plan ? crane(plan.craneId) : undefined

  const lines: string[] = [
    'NGT LIFTING PERMIT — CARGO ASSESSMENT',
    '='.repeat(44),
    `Reference    ${a.ref}  (version ${a.version})`,
    `Status       ${a.status === 'verified' ? 'VERIFIED' : 'ESTIMATED — NOT YET VERIFIED'}`,
    `Job          ${job?.ref ?? '—'}  ${job?.title ?? ''}`,
    `Vessel       ${job?.vessel ?? '—'}`,
    `Berth        ${job?.berth ?? '—'}`,
    `Assessed by  ${userName(a.createdBy)} at ${dateTime(a.createdAt)}`,
    '',
    'CARGO',
    '-'.repeat(44),
    `Type         ${a.cargoType.value}  [${a.cargoType.confidence}, ${SOURCE_LABEL[a.cargoType.source]}]`,
    `Material     ${a.material.value}  [${a.material.confidence}, ${SOURCE_LABEL[a.material.source]}]`,
    `Packaging    ${a.packaging.value}  [${a.packaging.confidence}, ${SOURCE_LABEL[a.packaging.source]}]`,
    `Dimensions   ${mm(a.dimensions.length.value)} × ${mm(a.dimensions.width.value)} × ${mm(a.dimensions.height.value)}  (± ${a.dimensions.toleranceMm} mm)`,
    `Weight       ${kg(a.weightKg.value)}  [${a.weightKg.confidence}, ${SOURCE_LABEL[a.weightKg.source]}]`,
    '',
    'LIFT CALCULATION',
    '-'.repeat(44),
    `Cargo        ${kg(calc.cargoKg)}`,
    `Rigging      ${kg(calc.riggingKg, { decimals: 1 })}`,
    `Contingency  ${kg(calc.contingencyKg)}  (${calc.contingencyPct} %)`,
    `GROSS        ${kg(calc.grossKg)}`,
    `Sling angle  ${plan?.slingAngleDeg ?? 60}°  (factor ×${calc.angleFactor.toFixed(2)})`,
    `Per leg      ${kg(calc.legLoadKg)}  against WLL ${kg(calc.slingWllKg)}`,
    '',
    'RIGGING',
    '-'.repeat(44),
    ...calc.rigging.map((r) => `${r.qty} × ${r.label} — ${r.detail} (${kg(r.totalKg, { decimals: 1 })})`),
    '',
    'CRANE',
    '-'.repeat(44),
    `Machine      ${c ? `${c.name} — ${c.model}` : '—'}`,
    `Config       ${calc.boomLabel}`,
    `Radius       ${metres(calc.radiusM, 0)}`,
    `Capacity     ${kg(calc.capacityKg)}`,
    `Utilisation  ${pct(calc.utilisationPct, 0)}  ${calc.overCapacity ? '*** OVER CHART — DO NOT LIFT ***' : calc.nearCapacity ? '*** ABOVE 85 % — APPROVAL REQUIRED ***' : '(within working limits)'}`,
    '',
    'LOAD CONDITION',
    '-'.repeat(44),
    `Lifting points  ${plan?.liftingPointsPresent ? `${plan.liftingPointCount} certified points` : 'NONE — sling arrangement, supervisor sign-off required'}`,
    `CoG offset      ${plan ? `${plan.cogOffsetMm.x} mm longitudinal, ${plan.cogOffsetMm.y} mm transverse` : '—'}`,
    ...(a.flags.length
      ? a.flags.map((f) => `Flag            [${f.severity.toUpperCase()}] ${f.label} — ${f.detail}`)
      : ['Flags           None raised']),
    '',
    'AUDIT',
    '-'.repeat(44),
    ...a.audit.slice(-5).map((e) => `${dateTime(e.at)}  ${e.actorName}  ${e.action}${e.field ? ` (${e.field}: ${e.from} → ${e.to})` : ''}`),
    '',
    a.status === 'verified'
      ? `Verified and locked by ${userName(a.verifiedBy ?? '')} on ${dateTime(a.verifiedAt ?? '')}.`
      : 'ESTIMATED VALUES — not valid as a lifting permit until verified.',
    'Generated by the NGT Cargo Assessment field app (prototype).',
  ]

  return lines.join('\n')
}

/** Clipboard write with a textarea fallback for browsers without permission. */
export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    if (navigator.clipboard && window.isSecureContext) {
      await navigator.clipboard.writeText(text)
      return true
    }
  } catch {
    /* fall through to the legacy path */
  }
  try {
    const ta = document.createElement('textarea')
    ta.value = text
    ta.setAttribute('readonly', '')
    ta.style.position = 'fixed'
    ta.style.opacity = '0'
    document.body.appendChild(ta)
    ta.select()
    const ok = document.execCommand('copy')
    document.body.removeChild(ta)
    return ok
  } catch {
    return false
  }
}
